import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import CursorTrail from "@/app/components/cursorTrail /CursorTrail";
import "./globals.css";
import Layout from "./components/layout";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <Layout>
          <CursorTrail />
          {children}
        </Layout>
      </body>
    </html>
  );
}
